name: New Feature Request
description: Request new feature(s) be added to PAMvieweR.
title: "[Request]: "
labels: ["enhancement"]
assignees: ["jmhatch"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: Contact details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@noaa.gov
    validations:
      required: true
  - type: checkboxes
    id: search
    attributes:
      label: Make sure a solution doesn't already exist for your problem
      description: Please search the existing [issues](https://github.com/jmhatch-NOAA/READ-PSB-PA-PAMvieweR/issues) and [documentation](https://jmhatch-noaa.github.io/READ-PSB-PA-PAMvieweR/reference/index.html) to see if a solution exists.
      options:
        - label: I have searched the existing issues and documentation.
          required: true
  - type: textarea
    id: feature
    attributes:
      label: What feature(s) would you like to add?
      description: Please provide a clear and concise description of the problem to be addressed by this feature request.
      value: "A concise description of your preferred solution."
    validations:
      required: true
      